name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show workspace
        run: |
          pwd
          ls -la
          ls -la babyshop || true

      - name: Install deps
        run: npm ci
        working-directory: babyshop

      - name: Build (Next.js static export via output:export)
        run: npm run build
        working-directory: babyshop

      - name: Check build output
        run: |
          ls -la
          ls -la out || true
        working-directory: babyshop

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHOP_AUTH_2825F }}
          channelId: live
          projectId: shop-auth-2825f
          entryPoint: babyshop
